site_name: Hello World 电控知识库

copyright: Copyright &copy; 2022-2023 Hello World Team, Zhejiang University

repo_url: https://github.com/ZJU-HelloWorld/Wiki
repo_name: Wiki
edit_uri: edit/main/docs/

theme:
  logo: img/rm.svg
  favicon: img/rm.svg

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - navigation.top
    - header.autohide

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  name: material
  language: zh

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - attr_list
  - md_in_html
  - tables

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZJU-HelloWorld
    - icon: fontawesome/solid/paper-plane
      link: mailto:<ZJU_HelloWorld@163.com>

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
