site_name: Hello World 电控知识库

copyright: Copyright &copy; 2022 - 2023 Hello World Team, Zhejiang University

repo_url: https://github.com/ZJU-HelloWorld/Wiki
repo_name: ZJU-HelloWorld/Wiki
edit_uri: edit/main/docs/

theme:
    logo: img/rm.svg
    favicon: img/rm.svg

    icon:
        edit: material/pencil 
        view: material/eye

    features:
        - content.code.copy
        - content.code.annotate 
        - content.action.edit
        - content.action.view
        - navigation.instant
        # - navigation.sections
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
        - navigation.tracking
        - toc.follow
        #     - toc.integrate
        - navigation.top
        - header.autohide
        - navigation.expand

    palette:
        # Palette toggle for light mode
        - scheme: default
          toggle:
              icon: material/lightbulb
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
              icon: material/lightbulb-outline
              name: Switch to light mode

    name: material
    language: zh

markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true
          permalink_title: Anchor link to this      section for reference
          toc_depth: 4
    - tables
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem
    - pymdownx.details
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji 
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.tabbed:
          alternate_style: true

    - pymdownx.tasklist:
          custom_checkbox: true

    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
    # generator: false
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/ZJU-HelloWorld
        - icon: fontawesome/solid/paper-plane
          link: mailto:<ZJU_HelloWorld@163.com>

plugins:
    - search
    - git-revision-date-localized:
          type: timeago
