site_name: Hello World 技术知识库

copyright: Copyright &copy; 2022 - 2024 Hello World Team, Zhejiang University

repo_url: https://github.com/ZJU-HelloWorld/Wiki
repo_name: ZJU-HelloWorld/Wiki
edit_uri: edit/main/docs/

theme:
    logo: assets/rm.svg
    favicon: assets/rm.svg

    icon:
        edit: material/pencil 
        view: material/eye

    features:
        - content.code.copy
        - content.code.annotate 
        - content.action.edit
        - content.action.view
      #   - navigation.instant
        # - navigation.sections
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - toc.follow
        - navigation.indexes
        #     - toc.integrate
        - navigation.top
        - header.autohide
        - navigation.expand
        - announce.dismiss
        
    custom_dir: overrides

    palette:
        # Palette toggle for light mode
        - scheme: default
          toggle:
              icon: material/lightbulb
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
              icon: material/lightbulb-outline
              name: Switch to light mode

    name: material
    language: zh

markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          slugify: !!python/object/apply:pymdownx.slugs.slugify
            kwds:
              case: lower
          permalink: true
          permalink_title: 链接到此节
          toc_depth: 4
    - tables
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem
    - pymdownx.details
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji 
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
             custom_icons:
                  - overrides/.icons
    - pymdownx.highlight:
          auto_title: true
          anchor_linenums: true
          linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.tabbed:
          alternate_style: true

    - pymdownx.tasklist:
          custom_checkbox: true

    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra: 
#     version:
#         provider: mike
#     consent:
#       title: Cookie consent
#       description: >-
#           We use cookies to recognize your repeated visits and preferences, as well
#           as to measure the effectiveness of our documentation and whether users
#           find what they're searching for. With your consent, you're helping us to
#           make our documentation better.
#       cookies:
#         analytics: Google Analytics 
    analytics:
        provider: google
        property: G-12BWRJ4SWG
        feedback:
            title: 此页面如何?
            ratings:
                - icon: material/star
                  name: 完全没帮助
                  data: 0
                  note: >-
                        感谢反馈！联系作者或点击标题右侧的浅色 pencil 标记来帮助改进XD
                - icon: material/star
                  name: 有点拉
                  data: 1
                  note: >-
                        感谢反馈！联系作者或点击标题右侧的浅色 pencil 标记来帮助改进XD
                - icon: material/star
                  name: 一般般
                  data: 2
                  note: >-
                        感谢反馈！联系作者或点击标题右侧的浅色 pencil 标记来帮助改进XD
                - icon: material/star
                  name: 还不错
                  data: 3
                  note: >-
                        感谢反馈！联系作者或点击标题右侧的浅色 pencil 标记来帮助改进XD
                - icon: material/star
                  name: 很棒！
                  data: 4
                  note: >- 
                        感谢反馈！

    # generator: false
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/ZJU-HelloWorld
        - icon: fontawesome/solid/paper-plane
          link: mailto:<ZJU_HelloWorld@163.com>

plugins:
      # - social
      - search
      - awesome-pages
      - i18n:
          material_alternate: true
          default_language: zh
          docs_structure: suffix #folder
          languages:
            zh: 
              name: 中文
              build: true
              site_name: Hello World 技术知识库
            en: 
              name: English
              build: true 
              site_name: Hello Wiki
          nav_translations: 
            en:
              测试指南: Testing
              贡献指南: Contribution
              关于: About
              开发指南: Development
              入门: Getting Started
              组件说明: Components Manual

      - glightbox
      - git-revision-date-localized:
            enable_creation_date: true
            type: iso_date
